### ISSUE TITLE
Member extraction algorithm doesn’t check for the right event stream

### ISSUE THREAD

**Issue by pietercolpaert** [Informatievlaanderen/VSDS-LDESClient-NifiProcessor#17]
In [LdesServiceImpl Line 53](https://github.com/Informatievlaanderen/VSDS-LDESClient-NifiProcessor/blob/main/ldes-client/src/main/java/be/vlaanderen/informatievlaanderen/ldes/client/services/LdesServiceImpl.java#L53), setting the subject as ANY is incorrect. This would fail when for example you’d have an LDES of LDESes, or when you would have a page that contains members of 2 different LDESes (not saying that would be a good practise)

Correct would:
 * You need to find the LDES event stream URI. 2 possibilities:
     * You instantiated the client with the LDES URI itself - which means you need to follow `tree:view` to find the first fragment itself and HTTP GET that one now. You did find the LDES event stream now though
     * You instantiated the client with a view or root fragment: you will find the LDES URI thorugh a `tree:view` relation, where the LDES URI is the subject.
 * The LDES URI should be used instead of the ANY in [LdesServiceImpl Line 53](https://github.com/Informatievlaanderen/VSDS-LDESClient-NifiProcessor/blob/main/ldes-client/src/main/java/be/vlaanderen/informatievlaanderen/ldes/client/services/LdesServiceImpl.java#L53)

**Comment by pietercolpaert** [comment]
This issue is not entirely solved I believe. If I correctly read the code, the behavior is now:

The page gets parsed for `tree:view` relations. The subject of the first encounter will be used as the LDES URI.

This should be:

The user passes a URI to the LDES client. When resolving this URI you’ll get a URL, possibly after redirection. This URL after redirection (or mentioned in the Location response header) is the tree:Node URL you’re currently at. This is the object of the `tree:view` triple.

So line 51: `Resource subjectId = model.listStatements(ANY, W3ID_TREE_VIEW, ANY)`

Should become: `Resource subjectId = model.listStatements(ANY, W3ID_TREE_VIEW, CURRENT_PAGE_URL)`

**Comment by Yalz** [comment]
Although I can follow your reasoning, and we can easily add this without trouble, i'm wondering if there is a scenario where you'd have multiple `tree:view` relations on a page/fragment ?

**Comment by pietercolpaert** [comment]
Yes, there certainly are: imagine an LDES server giving an overview on 1 page of all views it generated on top of existing event streams.

**Comment by pietercolpaert** [comment]
Mind that there is a possibility no `tree:view` is given. In that case we should check whether the configured URI we got was maybe the LDES URI itself. We thus need a fallback mechanism if no tree:view, dcterms:isPartOf or void:subset was found.

**Comment by Krieke** [comment]
The process should be that a Github issue is closed by the issue creator so that this person can validate that the issue is indeed solved.
