### ISSUE TITLE
Own StateManager vs NiFi's StateManager

### ISSUE THREAD

**Issue by ghsnd** [Informatievlaanderen/VSDS-LDESClient-NifiProcessor#27]
I know this is an early version, where - at this moment - there is a [StateManager](https://github.com/Informatievlaanderen/VSDS-LDESClient-NifiProcessor/blob/9f43b057b54ab6c29312bf99d51db7c77ff1f179/ldes-client/src/main/java/be/vlaanderen/informatievlaanderen/ldes/client/services/StateManager.java) class in the code to manage state. In the future you might consider using NiFi's [State Manager](https://nifi.apache.org/docs/nifi-docs/html/developer-guide.html#state_manager) or another state provider to make the state synchronised and possibly peristent in a cluster set-up.

**Comment by sverholen** [comment]
@ghsnd: NiFi's StateManager is suitable only for simple objects and it's memory size is limited to 1 Mb, making it unusable for most of our use-cases. A custom, persisted implementation of a StateManager is in the pipeline, but outside the scope of the MVP. We'll pick it up afterwards.
