### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by ghsnd** [Informatievlaanderen/VSDS-LDESClient-NifiProcessor#28]
In general using a logger in stead of `System.out` is considered good practice, although NiFi nicely catches everything logged to System.out and writes it to a log file. NiFi also provides a logger where you have more control (e.g. log level) which you can get by invoking `getLogger()` in a Processor. E.g. in `LDesClient`:
```java
@OnScheduled
public void onScheduled(final ProcessContext context) {
    getLogger().debug("Hello!");
    ldesService = new LdesServiceImpl(context.getProperty(DATASOURCE_URL).getValue());
}
```
You can pass this logger also to `LdesServiceImpl` for instance, but then this introduces dependencies to NiFi into the ldes-client module which is probably not what you want.
NiFi uses Logback so maybe you can use an SLF4J - Logback combo to avoid that extra dependency.

**Comment by Krieke** [comment]
@Yalz is this implemented?  The process should be that a Github issue is closed by the issue creator so that this person can validate that the issue is indeed solved.
