### ISSUE TITLE
StateManager never prunes state

### ISSUE THREAD

**Issue by ghsnd** [Informatievlaanderen/VSDS-LDESClient-NifiProcessor#30]
[StateManager](https://github.com/Informatievlaanderen/VSDS-LDESClient-NifiProcessor/blob/9f43b057b54ab6c29312bf99d51db7c77ff1f179/ldes-client/src/main/java/be/vlaanderen/informatievlaanderen/ldes/client/services/StateManager.java#L14):  `processedFragments` and `processedMembers` can potentially grow indefinitely. Maybe implement some retention policy in a future release?

**Comment by Yalz** [comment]
This is a valid concern that we're keeping in mind and that we'll address in future releases

**Comment by sverholen** [comment]
Fixed by commits for performance improvement.
