### ISSUE TITLE
Close resources

### ISSUE THREAD

**Issue by ghsnd** [Informatievlaanderen/VSDS-LDESClient-NifiProcessor#32]
[LdesFragment.java](https://github.com/Informatievlaanderen/VSDS-LDESClient-NifiProcessor/blob/9f43b057b54ab6c29312bf99d51db7c77ff1f179/ldes-client/src/main/java/be/vlaanderen/informatievlaanderen/ldes/client/valueobjects/LdesFragment.java#L40):

Don't forget to close the client to free up resources. `CloseableHttpClient` is an `AutoCloseable`, so:

```java
try (CloseableHttpClient httpClient = HttpClients.createDefault()) {
    HttpResponse httpResponse = httpClient.execute(new HttpGet(url));
    ...

} catch(...) {
    // handle errors
}
```

Also, check the status of `httpResponse` and handle accordingly.

**Comment by Krieke** [comment]
The process should be that a Github issue is closed by the issue creator so that this person can validate that the issue is indeed solved.
