### ISSUE TITLE
LDES members synchronization fails to http client sink 

### ISSUE THREAD

**Issue by zargha** [Informatievlaanderen/VSDS-LDESClient-NifiProcessor#41]
### The Problem
The problem occurred while testing the e2e demo for sprint 2. First `alfa.json.ld`, `beta.json.ld` and `gamma.json.ld` fragments have been replicated which results in total amount of 501 members. 
Next for the synchronization, `delta.jsonld` and `epsilon.jsonld` have uploaded to ldes server simulator. During the synchronization process, it fails.

### Environment
**Components under test**
- vsds/ldes-server-simulator
- vsds/ldes-client-sink
- vsds/ldes-client-workflow
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20
```
```
$ docker --version
Docker version 20.10.17, build 100c701
$ docker-compose --version
docker-compose version 1.29.2, build 5becea4c

Google Chrome
Version 102.0.5005.115 (Official Build) (64-bit)
```
### Error logs
[logs_sync.txt](https://github.com/Informatievlaanderen/VSDS-LDESClient-NifiProcessor/files/8928625/logs_sync.txt)

Screenshot:
![image](https://user-images.githubusercontent.com/63961369/174323800-177735db-6a27-4c88-b7d5-e85ecf6785b0.png)
### Steps to reproduce
1. Start you system as described [here]( https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/20220607.demo-1#start-systems)
2. Setup the demo as described [here](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/20220607.demo-1#setup-demo)
3. Start the replication as described [here](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/20220607.demo-1#replicate)
4. Start the synchronization as described [here](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/20220607.demo-1#synchronize)
5. During the synchronization process, send continuous `GET/` requests to ldes client sink at `http://localhost:9003`

During step 5 the problem occurs.

**Comment by Yalz** [comment]
Hi @zargha ,
For this issue, we recently pushed a fix. Could you try again?
Since after manual validation I reach 617 members in the sink.

**Comment by rorlic** [comment]
In your [logs_sync.txt](https://github.com/Informatievlaanderen/VSDS-LDESClient-NifiProcessor/files/8928625/logs_sync.txt) file I see a `Broken pipe` exception and most likely your `InvokeHTTP processor` settings for `Failure` handling (see `Relations` tab) are set to `Terminate`. Can you please try to reproduce this with this setting set to `Retry`?

**Comment by zargha** [comment]
> In your [logs_sync.txt](https://github.com/Informatievlaanderen/VSDS-LDESClient-NifiProcessor/files/8928625/logs_sync.txt) file I see a `Broken pipe` exception and most likely your `InvokeHTTP processor` settings for `Failure` handling (see `Relations` tab) are set to `Terminate`. Can you please try to reproduce this with this setting set to `Retry`?

@rorlic  can you provide against which git tag i should test this?

**Comment by zargha** [comment]
Issue tested and fixed in https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/pkgs/container/ldes-client-sink/28499553?tag=20220714T1423
