### ISSUE TITLE
LDES members replication fails for second fragment

### ISSUE THREAD

**Issue by zargha** [Informatievlaanderen/VSDS-LDESClient-NifiProcessor#45]
### The Problem
The problem occurred while testing the [e2e 20220705.demo1](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/20220705.demo1).
The problem occurs during the [Scenario: data set contains 2 fragments](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/20220705.demo1#scenario-data-set-contains-2-fragments). `beta.jsonld` cannot be replicated to ldes server.

Fragments uploaded:
```
curl -X POST http://localhost:9001/ldes -H 'Content-Type: application/json-ld' -d '@gipod-server-simulator/data/scenario3/alfa.jsonld'
curl -X POST http://localhost:9001/ldes -H 'Content-Type: application/json-ld' -d '@gipod-server-simulator/data/scenario3/beta.jsonld'
{"content-type":"application/json-ld","cache-control":"public, max-age=604800, immutable","id":"/api/v1/ldes/mobility-hindrances?generatedAtTime=2022-05-20T09:58:15.867Z"}{"content-type":"application/json-ld","cache-control":"public, max-age=604800, immutable","id":"/api/v1/ldes/mobility-hindrances?generatedAtTime=2022-05-25T10:22:45.82Z"}%                                                                                                                  
```
### Environment
**Components under test**
- ghcr.io/informatievlaanderen/ldes-server:20220711T1053
- vsds/ldes-client-workflow
- ghcr.io/informatievlaanderen/ldes-server-simulator:20220629t1521
- mongo
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20
```
```
$ docker --version
Docker version 20.10.17, build 100c701
$ docker compose version
Docker Compose version v2.6.0
```
```
$ git branch
feature/VSDSPUB-62-e2e-test
```
### Screenhots:
gipod-server-simulator:
![image](https://user-images.githubusercontent.com/63961369/178755277-33def9f0-335d-491f-9c84-e74d2b201552.png)

mongodb:
![image](https://user-images.githubusercontent.com/63961369/178756357-4876464a-d365-47fc-bb8e-3876821434ca.png)

ldes-server:
![image](https://user-images.githubusercontent.com/63961369/178756757-fc71fbaf-8678-4489-bb33-cd4d3915b53d.png)

### Steps to reproduce
1. Setup the demo as described [here](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/20220705.demo1#setup-demo)
2. [Scenario: replication has not yet started](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/20220705.demo1#scenario-replication-has-not-yet-started)
3. [Scenario: replication has just started](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/20220705.demo1#scenario-replication-has-just-started)
4. [Scenario: data set contains 2 fragments](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/20220705.demo1#scenario-data-set-contains-2-fragments)

The problem occurs during step 4.

**Comment by Krieke** [comment]
@zargha can you please try to reproduce? This should have been fixed with the retry mechanism that was implemented in the NiFi workflow

**Comment by zargha** [comment]
> @zargha can you please try to reproduce? This should have been fixed with the retry mechanism that was implemented in the NiFi workflow

yes i will test this!

**Comment by zargha** [comment]
Issue tested and closed using these [tags](https://vlaamseoverheid.atlassian.net/wiki/spaces/VSDSPUB/pages/6124077094/UAT+Sprint+5#Repositories-%26-Tags-(SUT))
